export const FETCH_RESTUARANTS_SUCCESS = 'FETCH_RESTUARANTS_SUCCESS'
export const FETCH_RESTUARANTS_FAILURE = 'FETCH_RESTUARANTS_FAILURE'
export const FETCH_ADD_RESTUARANTS = 'FETCH_ADD_RESTUARANTS'
export const LOADING = 'LOADING'